services:
  aether-frontend:
    image: aether-ui:latest
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_WS_URL=${VITE_WS_URL}
    container_name: aether-ui
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - aether-network

networks:
  aether-network:
    external: true
