version: '3.8'

services:
  aether-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aether-ui
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - aether-network
    command: ["nginx", "-g", "daemon off;"]

networks:
  aether-network:
    external: true
