syntax = "proto3";

package featurePipeline;


// Map Enums to Python constants
enum SourceFormat {
    UNKNOWN_FORMAT = 0;
    CSV = 1;
    PARQUET = 2;
    AVRO = 3;
    JSON = 4;
    IMAGE = 5;
    TEXT = 6;
    AUDIO = 7;
    VIDEO = 8;
    BINARY = 9;
}

enum TransformationType {
    UNKNOWN_TYPE = 0;
    SQL = 1;
    PYTHON_UDF = 2;
    AGGREGATION = 3;
}

enum ReadPolicy {
    FULL_READ = 0;
    NEW_VALUES = 1;
}


// Preview Flow Request & Response
message AggregationConfig {
    repeated string entity_keys = 1;
    string time_column = 2;
    string features_config_json = 3; 
    repeated string windows = 4;
}

message PreviewRequest {
    string location_uri = 1;
    SourceFormat source_format = 2;
    TransformationType transform_type = 3;
    string transform_definition = 4;

    // Configuration
    string connection_options_json = 5;
    int32 limit = 6;

    // UDF Specific
    repeated string requirements = 7;
    repeated string target_datasets = 8;

    // Aggregation Specific
    AggregationConfig aggregation_config = 9;
}

message PreviewResponse {
    // Key: dataset_name, Value: JSON string list of records
    map<string, string> results_json = 1;
}


// Run Flow Request & Response (Background Tasks)
message RunRequest {
    string location_uri = 1;
    string output_uri = 2;
    SourceFormat source_format = 3;
    TransformationType transform_type = 4;
    string transform_definition = 5;

    // Configuration
    string connection_options_json = 6;
    double last_updated = 7; // Unix timestamp
    ReadPolicy read_policy = 8;

    // UDF Specific
    repeated string requirements = 9;

    // Select Target Dataset
    repeated string target_datasets = 10;

    // Aggregation Specific
    AggregationConfig aggregation_config = 11;

    bool sync_online = 12;

    optional int32 time_to_live = 13;

    string feature_group_id = 14; 
    optional string webhook_url = 15;

    string join_key = 16;
}

message RunResponse {
    string feature_group_id = 1;
    string status = 2;
    string message = 3;
}


// Materialization Offline and Online
message FeatureGroupMeta {
    string alias = 1;
    string location_uri = 2;
    repeated string features = 3;
}

message MaterializeViewRequest {
    string job_id = 1;
    string view_id = 2;
    string join_key = 3;
    repeated FeatureGroupMeta feature_groups = 4;
    string output_uri = 5; // s3://aether-offline-store/materialized/{view_id}/{job_id}/
    optional string webhook_url = 6;
}

message MaterializeViewResponse {
    string job_id = 1;
    string status = 2;
    string message = 3;
}


// In-System Execution Request & Response
message ExecuteScriptRequest {
    string script_code = 1;
    repeated string requirements = 2;
    string dataset_uri = 3;
}

message ExecuteScriptResponse {
    string status = 1; 
    string logs = 2;   
    string error_message = 3; 
    string analytics_json = 4;
}


// Streaming Flow Request & Response
message StartStreamingRequest {
    string fg_id = 1;
    string fg_name = 2;
    string topic_name = 3;
    string kafka_servers = 4;
    string join_key = 5;
    SourceFormat source_format = 6;

    bool has_transformation = 7;
    TransformationType transformation_type = 8;
    string transformation_definition = 9;

    // Sink configuration
    string output_uri = 10;           // s3://aether-offline-store/feature_groups/{fg_id}
    repeated string entity_keys = 11; // Primary key columns for Redis upsert
    optional int32 time_to_live = 12; // Redis TTL (seconds). Default = 7 days
    bool sync_online = 13;            // Whether to write to Online Store (Redis)
}

message StopStreamingRequest {
    string fg_id = 1;
}

message StreamingResponse {
    bool success = 1;
    string message = 2;
}


// Service Interface
service PipelineService {
    // Quick Formula Test & UI Data Preview
    rpc PreviewFeatureGroup (PreviewRequest) returns (PreviewResponse);

    // Persists files to Feature Storage and pushes data to Redis
    rpc RunBatchPipeline (RunRequest) returns (RunResponse);

    // Join file parquet for feature view
    rpc MaterializeFeatureView (MaterializeViewRequest) returns (MaterializeViewResponse);

    // Run user Python code on Ray Cluster
    rpc ExecuteUserScript (ExecuteScriptRequest) returns (ExecuteScriptResponse);

    // Activate a background Ray Actor to listen to Kafka
    rpc StartStreamingPipeline (StartStreamingRequest) returns (StreamingResponse);

    // Terminate the Ray Actor and stop the flow
    rpc StopStreamingPipeline (StopStreamingRequest) returns (StreamingResponse);
}
