"""add last_synced_at to data_sources

Revision ID: c6a7ca4f0291
Revises: cfc701b11bc1
Create Date: 2026-03-28 07:14:27.695917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a7ca4f0291'
down_revision: Union[str, None] = 'cfc701b11bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('last_synced_at', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'last_synced_at')
    # ### end Alembic commands ###
