"""initial_aether_schema

Revision ID: da47d12740b6
Revises: 
Create Date: 2026-03-15 11:10:20.878794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da47d12740b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_format', sa.String(length=20), nullable=True),
    sa.Column('location_uri', sa.String(length=255), nullable=False),
    sa.Column('timestamp_field', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('join_key', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feature_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transformations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('t_type', sa.String(length=20), nullable=True),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('window_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feature_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('transformation_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_feature_groups_entity_id'), 'feature_groups', ['entity_id'], unique=False)
    op.create_index(op.f('ix_feature_groups_source_id'), 'feature_groups', ['source_id'], unique=False)
    op.create_index(op.f('ix_feature_groups_transformation_id'), 'feature_groups', ['transformation_id'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['feature_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'name', 'version', name='unique_feature_version')
    )
    op.create_index(op.f('ix_features_group_id'), 'features', ['group_id'], unique=False)
    op.create_table('feature_view_members',
    sa.Column('view_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['view_id'], ['feature_views.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id', 'feature_id')
    )
    op.create_index(op.f('ix_feature_view_members_feature_id'), 'feature_view_members', ['feature_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_view_members_feature_id'), table_name='feature_view_members')
    op.drop_table('feature_view_members')
    op.drop_index(op.f('ix_features_group_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_feature_groups_transformation_id'), table_name='feature_groups')
    op.drop_index(op.f('ix_feature_groups_source_id'), table_name='feature_groups')
    op.drop_index(op.f('ix_feature_groups_entity_id'), table_name='feature_groups')
    op.drop_table('feature_groups')
    op.drop_table('transformations')
    op.drop_table('feature_views')
    op.drop_table('entities')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
